Added Usual Stop command and fixed stop command when Overrun Error fl…ag. (#9)
CONPROSYS/LINUX-SDK_driver pull request #10
Opened 2019-03-22 14:31 UTC by Syunsuke-Okamoto

# The cpsaio driver updated.
* Added Usual Stop command.
* Fixed stop command when Overrun Error flag.

2019-03-24 23:44 UTC, ura1231 requested changes
１点確認事項を追記しました。
確認をお願いします。

2019-03-24 23:44 UTC, ura1231 commented on cps-drivers/aio/cpsaio.c
> +				wAnalogStatus = 0;
(cpsaio.h)
///< ステータスマクロ
#define CPS_AIO_AIS_BUSY		0x0001
#define CPS_AIO_AIS_START_TRG	0x0002
#define CPS_AIO_AIS_DATA_NUM	0x0010
#define CPS_AIO_AIS_OFERR		0x00010000
#define CPS_AIO_AIS_SCERR		0x00020000

803  if( ulTmpStatus & (CPS_AIO_AIS_SCERR | CPS_AIO_AIS_OFERR) )
804  {
805      if( ulTmpStatus & CPS_AIO_AIS_BUSY ){

803行目でフィルタされるため、805行目の条件が真になることはありません。
意図通りの実装であるか、確認をお願いします。

2019-03-25 01:39 UTC, Syunsuke-Okamoto commented on cps-drivers/aio/cpsaio.c
> +				wAnalogStatus = 0;
Thanks you your comment.
I checked these codes.
These code is running right.

At first, line 803 means  : 

| pattern [hex] | true / false |
|:---|:---|
| 10000 | true |
| 20000 | true |
| 10001 | true |
| 20001 | true |
| 00001 | false |

This does not pass  AIS_BUSY only.
This need pass OF_ERR or SC_ERR.

At, second line 805 means : 

| pattern [hex] | true / false |
|:---|:---|
| 10000 | false |
| 20000 | false |
| 10001 | true |
| 20001 | true |

This need pass (OF_ERR and AIS_BUSY) or (SC_ERR and AIS_BUSY).

Best regards,

2019-03-25 02:07 UTC, ura1231 approved these changes

2019-03-25 02:09 UTC, ura1231 commented on cps-drivers/aio/cpsaio.c
> +				wAnalogStatus = 0;
I confirmed to be your intended design.

2019-03-25 03:15 UTC, merged